name: test PR

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  j1:
    name: test hello world
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: test hello world
        uses: ./hello-world
