name: update v1 tag

on:
  release:
    types:
      - published
      - edited

jobs:
  actions-tagger:
    runs-on: windows-latest
    steps:
      - uses: Actions-R-Us/actions-tagger@v2.0.2
        with:
          publish_latest_tag: true
